# Creating the deployment for the code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codechallenge-test
  labels:
    app: codechallenge-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codechallenge-test
  template:
    metadata:
      labels:
        app: codechallenge-test
    spec:
      containers:
        name: codechallenge-test
        image: codechallenge-test:1.0.0
        ports:
        = containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

# Creating the service to support the code deployment
apiVersion: v1
kind: Service
metadata:
  name: codechallenge-test-service
  labels:
    app: codechallenge-test
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 8000
  selector:
    app: codechallenge-test