# Creating the deployment for the Iris FastAPI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-challenge
  labels:
    app: code-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-challenge
  template:
    metadata:
      labels:
        app: code-challenge
    spec:
      containers:
      - name: code-challenge
        image: code-challenge:1.0.0
        ports:
        = containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

# Creating the service to support the deployment
apiVersion: v1
kind: Service
metadata:
  name: code-challenge-service
  labels:
    app: code-challenge
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: code-challenge