PATHS:
    Project_path: './'
    models_path: 'models/'
    data_path: 'data/'

train_file_name: data_merged.parquet
model_name : xgboost.pkl
model_name_random_forest : rf.pkl
final_feature_list : final_features.csv
feature_list_before_fs: final_features_before_fs.csv
predictions_file_name: predictions.csv
base_model : baseline_model.pkl
best_params_rf: best_params_rf.json


param_grid :
    xgb : { 
          colsample_bytree: [0.7, 0.3],
          gamma: [0, 0.1, 0.2,0.5],
          learning_rate: [0.003, 0.3],
          max_depth: [2,3,4,5,6],
          n_estimators : [100,200,300,400,500], 
          subsample: [0.7, 0.3]
         }


# Parameters for random forest regressor
# Create the parameter grid based on the results of random search
parameter_grid_rf:
    param_grid : {
    'bootstrap': [True], # Consider bootstapping
    'max_features': [2, 3, 4, 5, 6], # number of features to consider at every split
    'n_estimators': [100, 200, 500], # Number of trees in random forest
    'max_depth': [10, 20, 30, 40, 50, 60, 70, 80], # Maximum number of levels in tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split a node
    'min_samples_leaf': [1, 2, 4], # Minimum number of samples required at each leaf node
    'random_state': [2022] # Random state
    }



# parameter_grid_rf:
#     param_grid : {
#     'bootstrap': [True], # Consider bootstapping
#     'max_features': [2], # number of features to consider at every split
#     'n_estimators': [100], # Number of trees in random forest
#     'max_depth': [10, 20, 30], # Maximum number of levels in tree
#     'min_samples_split': [2], # Minimum number of samples required to split a node
#     'min_samples_leaf': [1, 2, 4], # Minimum number of samples required at each leaf node
#     'random_state': [2022]
# }




lasso_params: 
    params : {
        'alpha':[0.02, 0.024, 0.025, 0.026, 0.03]
        } # Tuning parameter for the Lasso model that controls the degree of regularization.

# logging_params:
#       num_rounds: 500
#       xgb: {
#         max_depth : 18,  # control model complexity.
#         min_child_weight: 7.0, # control model complexity.
#         reg_lambda: 0.39,  # L2 regularization term on weights.
#         reg_alpha: 42.0, # L1 regularization
#         subsample : 1.0, # add randomness to make training robust to noise.
#         colsample_bytree : 0.96, # add randomness to make training robust to noise.
#         eta: 0.5, # step size shrinkage used in update to prevents overfitting. Also called learning rate.
#         gamma: 2.95,  # control model complexity. Used for pruning the tree. gain-gamma is the minimum loss reduction required to make a split.
#         eval_metric : ['rmse'], # evaluation metric
#         objective : 'reg:squarederror',
#         tree_method : 'gpu_hist',
#         seed : 2022
#         }

lasso : ['TE_crystal_supergroup_Categorify' ,'TE_crystal_type_Categorify',
 'TE_groups_Categorify', 'previous_adamantium','TE_ts_weekday_Categorify',
 'TE_ts_day_Categorify', 'TE_tracking_times_Categorify',
 'TE_ts_month_Categorify' , 'TE_cycle_Categorify',
 'TE_human_behavior_report_Categorify', 'TE_unnamed_7_Categorify',
 'CE_TE_groups_Categorify', 'expected_final_factor_x', 'final_factor_x']

unnamed_col: ['unnamed:0', 'unnamed:17', 'unnamed:7']

cat_cols: ['super_hero_group', 'place','tracking_times','crystal_supergroup', 'crystal_type','unnamed_7','human_behavior_report','cycle','groups']

continous_cols_before_preprocess: ['tracking', 'human_measure', 'crystal_weight','expected_factor_x',
 'previous_factor_x','first_factor_x','expected_final_factor_x','final_factor_x','previous_adamantium','etherium_before_start',
'raw_kryptonite','argon','pure_seastone']


remove_cols: ['super_hero_group_Categorify', 'groups']

continous_cols: ['TE_super_hero_group_Categorify',
       'TE_place_Categorify', 'TE_tracking_times_Categorify',
       'TE_crystal_supergroup_Categorify', 'TE_crystal_type_Categorify',
       'TE_unnamed_7_Categorify', 'TE_human_behavior_report_Categorify',
       'TE_cycle_Categorify', 'TE_groups_Categorify',
       'CE_TE_super_hero_group_Categorify', 'CE_TE_place_Categorify',
       'CE_TE_tracking_times_Categorify',
       'CE_TE_crystal_supergroup_Categorify', 'CE_TE_crystal_type_Categorify',
       'CE_TE_unnamed_7_Categorify', 'CE_TE_human_behavior_report_Categorify',
       'CE_TE_cycle_Categorify', 'CE_TE_groups_Categorify', 'tracking', 'human_measure', 'crystal_weight','expected_factor_x',
        'previous_factor_x','first_factor_x','expected_final_factor_x','final_factor_x','previous_adamantium','etherium_before_start',
        'raw_kryptonite','argon','pure_seastone','CE_TE_ts_weekday_Categorify', 
        'CE_TE_ts_day_Categorify', 'CE_TE_ts_month_Categorify','TE_ts_weekday_Categorify', 'TE_ts_day_Categorify', 'TE_ts_month_Categorify']

one_hot_encoded_weekday: ['ts_weekday_0', 'ts_weekday_1', 'ts_weekday_2', 'ts_weekday_3',
       'ts_weekday_4', 'ts_weekday_5', 'ts_weekday_6']

vars_with_na : ['crystal_weight',
 'first_factor_x',
 'final_factor_x',
 'previous_adamantium',
 'etherium_before_start',
 'expected_start',
 'start_subprocess1',
 'start_critical_subprocess1',
 'predicted_process_end',
 'process_end',
 'subprocess1_end',
 'reported_on_tower',
 'opened',
 'raw_kryptonite',
 'argon',
 'pure_seastone',
 'groups']

duplicate_cols: ['unnamed_17']

cat_cols_feature_selection: ['super_hero_group_Categorify',
  'place_Categorify',
  'tracking_times_Categorify',
  'crystal_supergroup_Categorify',
  'crystal_type_Categorify',
  'unnamed_7_Categorify',
  'human_behavior_report_Categorify',
  'cycle_Categorify',
  'groups_Categorify',
  'groups','NA_crystal_weight', 'NA_first_factor_x', 'NA_final_factor_x',
  'NA_previous_adamantium', 'NA_etherium_before_start',
  'NA_expected_start', 'NA_start_subprocess1',
  'NA_start_critical_subprocess1', 'NA_predicted_process_end',
  'NA_process_end', 'NA_subprocess1_end', 'NA_reported_on_tower',
  'NA_opened', 'NA_raw_kryptonite', 'NA_argon',
  'NA_pure_seastone', 'NA_groups', 'place', 'tracking_times', unnamed_7,'human_behavior_report', 'crystal_supergroup',
  'cycle','ts_weekday_0', 'ts_weekday_1', 'ts_weekday_2', 'ts_weekday_3',
  'ts_weekday_4', 'ts_weekday_5', 'ts_weekday_6']
target_col: ['target']

continous_col_feature_selection: ['TE_super_hero_group_Categorify',
       'TE_place_Categorify', 'TE_tracking_times_Categorify',
       'TE_crystal_supergroup_Categorify', 'TE_crystal_type_Categorify',
       'TE_unnamed_7_Categorify', 'TE_human_behavior_report_Categorify',
       'TE_cycle_Categorify', 'TE_groups_Categorify',
       'CE_TE_super_hero_group_Categorify', 'CE_TE_place_Categorify',
       'CE_TE_tracking_times_Categorify',
       'CE_TE_crystal_supergroup_Categorify', 'CE_TE_crystal_type_Categorify',
       'CE_TE_unnamed_7_Categorify', 'CE_TE_human_behavior_report_Categorify',
       'CE_TE_cycle_Categorify', 'CE_TE_groups_Categorify', 'tracking', 'human_measure', 'crystal_weight','expected_factor_x',
       'previous_factor_x','first_factor_x','expected_final_factor_x','final_factor_x','previous_adamantium','etherium_before_start',
       'raw_kryptonite','argon','pure_seastone','CE_TE_ts_weekday_Categorify', 
       'CE_TE_ts_day_Categorify', 'CE_TE_ts_month_Categorify','TE_ts_weekday_Categorify', 'TE_ts_day_Categorify', 
       'TE_ts_month_Categorify']

categorify_columns: ['super_hero_group', 'place','tracking_times','crystal_supergroup', 'crystal_type','unnamed_7','human_behavior_report','cycle','groups','ts_weekday', 'ts_day', 'ts_month']

target_encode_columns: ['super_hero_group_Categorify', 'place_Categorify','tracking_times_Categorify','crystal_supergroup_Categorify', 'crystal_type_Categorify',
                        'ts_weekday_Categorify', 'ts_day_Categorify', 'ts_month_Categorify','unnamed_7_Categorify','human_behavior_report_Categorify','cycle_Categorify','groups_Categorify']

count_encode_columns:  ['TE_super_hero_group_Categorify', 'TE_place_Categorify','TE_tracking_times_Categorify','TE_crystal_supergroup_Categorify', 'TE_crystal_type_Categorify','TE_unnamed_7_Categorify',
'TE_human_behavior_report_Categorify','TE_cycle_Categorify','TE_groups_Categorify', 'TE_ts_weekday_Categorify', 'TE_ts_day_Categorify', 'TE_ts_month_Categorify']

cols_to_drop : ["super_hero_group"]

date_cols: ['when',  'expected_start', 'start_process',
            'start_subprocess1',
            'predicted_process_end', 'process_end', 'subprocess1_end',
            'reported_on_tower', 'opened']

required_columns : ['super_hero_group_Categorify',
  'place_Categorify',
  'tracking_times_Categorify',
  'crystal_supergroup_Categorify',
  'crystal_type_Categorify',
  'unnamed_7_Categorify',
  'human_behavior_report_Categorify',
  'cycle_Categorify',
  'groups_Categorify',
  'groups','NA_crystal_weight', 'NA_first_factor_x', 'NA_final_factor_x',
  'NA_previous_adamantium', 'NA_etherium_before_start',
  'NA_expected_start', 'NA_start_subprocess1',
  'NA_start_critical_subprocess1', 'NA_predicted_process_end',
  'NA_process_end', 'NA_subprocess1_end', 'NA_reported_on_tower',
  'NA_opened',  'NA_raw_kryptonite', 'NA_argon',
  'NA_pure_seastone', 'NA_groups', 'place', 'tracking_times', unnamed_7,'human_behavior_report', 'crystal_supergroup',
  'cycle','TE_super_hero_group_Categorify',
       'TE_place_Categorify', 'TE_tracking_times_Categorify',
       'TE_crystal_supergroup_Categorify', 'TE_crystal_type_Categorify',
       'TE_unnamed_7_Categorify', 'TE_human_behavior_report_Categorify',
       'TE_cycle_Categorify', 'TE_groups_Categorify',
       'CE_TE_super_hero_group_Categorify', 'CE_TE_place_Categorify',
       'CE_TE_tracking_times_Categorify',
       'CE_TE_crystal_supergroup_Categorify', 'CE_TE_crystal_type_Categorify',
       'CE_TE_unnamed_7_Categorify', 'CE_TE_human_behavior_report_Categorify',
       'CE_TE_cycle_Categorify', 'CE_TE_groups_Categorify', 'tracking', 'human_measure', 'crystal_weight','expected_factor_x',
        'previous_factor_x','first_factor_x','expected_final_factor_x','final_factor_x','previous_adamantium','etherium_before_start',
        'raw_kryptonite','argon','pure_seastone', 
        'TE_ts_weekday_Categorify', 'TE_ts_day_Categorify', 'TE_ts_month_Categorify', 'ts_weekday_Categorify', 'ts_day_Categorify', 'ts_month_Categorify', 'ts_weekday', 'ts_day', 'ts_month',
        'CE_TE_ts_weekday_Categorify', 'CE_TE_ts_day_Categorify', 'CE_TE_ts_month_Categorify']